#ifndef OLATUAK_H
#define OLATUAK_H

#include "game02.h"

void Olatua1(JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6);
void Olatua2(JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P7, JOKO_ELEMENTUA P8, JOKO_ELEMENTUA P9, JOKO_ELEMENTUA P10);

#endif
