#ifndef OLATUAK_H
#define OLATUAK_H

#include "game02.h"

void Olatua1(JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6);
void Olatua2(JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P7, JOKO_ELEMENTUA P8, JOKO_ELEMENTUA P9, JOKO_ELEMENTUA P10);
void Olatua3(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26);
void Olatua7(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12);
void Olatua4(JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24);
void Olatua5(JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12);
void Olatua6(JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12);
void Olatua8(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P27, JOKO_ELEMENTUA P28, JOKO_ELEMENTUA P29, JOKO_ELEMENTUA P30);
void Olatua9(JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12, JOKO_ELEMENTUA P13, JOKO_ELEMENTUA P14);
void Olatua10(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12, JOKO_ELEMENTUA P13, JOKO_ELEMENTUA P14);
void Olatua11(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P27, JOKO_ELEMENTUA P28, JOKO_ELEMENTUA P29, JOKO_ELEMENTUA P30, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12, JOKO_ELEMENTUA P13, JOKO_ELEMENTUA P14);
void Olatua13(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P15, JOKO_ELEMENTUA P16, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P27, JOKO_ELEMENTUA P28, JOKO_ELEMENTUA P29, JOKO_ELEMENTUA P30, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12, JOKO_ELEMENTUA P13, JOKO_ELEMENTUA P14, JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P7, JOKO_ELEMENTUA P8, JOKO_ELEMENTUA P9, JOKO_ELEMENTUA P10);
void Olatua12(JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P27, JOKO_ELEMENTUA P28, JOKO_ELEMENTUA P29, JOKO_ELEMENTUA P30, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12, JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P7, JOKO_ELEMENTUA P8, JOKO_ELEMENTUA P9, JOKO_ELEMENTUA P10);
void Olatua14(JOKO_ELEMENTUA P15, JOKO_ELEMENTUA P16, JOKO_ELEMENTUA P17, JOKO_ELEMENTUA P18, JOKO_ELEMENTUA P19, JOKO_ELEMENTUA P20, JOKO_ELEMENTUA P21, JOKO_ELEMENTUA P22, JOKO_ELEMENTUA P23, JOKO_ELEMENTUA P24, JOKO_ELEMENTUA P25, JOKO_ELEMENTUA P26, JOKO_ELEMENTUA P27, JOKO_ELEMENTUA P28, JOKO_ELEMENTUA P29, JOKO_ELEMENTUA P30, JOKO_ELEMENTUA P11, JOKO_ELEMENTUA P12, JOKO_ELEMENTUA P13, JOKO_ELEMENTUA P14, JOKO_ELEMENTUA P1, JOKO_ELEMENTUA P2, JOKO_ELEMENTUA P3, JOKO_ELEMENTUA P4, JOKO_ELEMENTUA P5, JOKO_ELEMENTUA P6, JOKO_ELEMENTUA P7, JOKO_ELEMENTUA P8, JOKO_ELEMENTUA P9, JOKO_ELEMENTUA P10);
void etsaienPosizioaHasieratu(int pos[]);
#endif

